# Generated by Django 6.1 on 2026-08-25 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=16, verbose_name='status')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (ms)')),
                ('method', models.CharField(max_length=10, verbose_name='method')),
                ('url', models.TextField(verbose_name='url')),
                ('request_headers', models.JSONField(blank=True, default=dict, verbose_name='request headers')),
                ('request_body', models.TextField(blank=True, verbose_name='request body')),
                ('request_body_omission', models.CharField(blank=True, choices=[('disabled', 'Body storage disabled'), ('too_large', 'Body above the size limit'), ('binary', 'Body is not text'), ('streamed', 'Body was streamed')], max_length=16, verbose_name='request body omitted because')),
                ('retriable', models.BooleanField(default=False, verbose_name='retriable')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='context')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='status code')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('response_headers', models.JSONField(blank=True, default=dict, verbose_name='response headers')),
                ('response_body', models.TextField(blank=True, verbose_name='response body')),
                ('response_body_omission', models.CharField(blank=True, choices=[('disabled', 'Body storage disabled'), ('too_large', 'Body above the size limit'), ('binary', 'Body is not text'), ('streamed', 'Body was streamed')], max_length=16, verbose_name='response body omitted because')),
                ('response_truncated', models.BooleanField(default=False, verbose_name='response truncated')),
            ],
            options={
                'verbose_name': 'HTTP request log',
                'verbose_name_plural': 'HTTP request logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='outbound_ht_status_4d1049_idx'), models.Index(fields=['status_code'], name='outbound_ht_status__6f91db_idx')],
            },
        ),
        migrations.CreateModel(
            name='HttpRequestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('trigger', models.CharField(choices=[('request', 'Initial request'), ('admin', 'Retry from the admin'), ('command', 'Retry from a management command'), ('code', 'Retry from code')], max_length=16, verbose_name='trigger')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='status code')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='outbound_http.httprequestlog', verbose_name='HTTP request log')),
            ],
            options={
                'verbose_name': 'request attempt',
                'verbose_name_plural': 'request attempts',
                'ordering': ('-started_at',),
            },
        ),
    ]
