# Generated by Django 6.1 on 2026-08-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound_http', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='httprequestlog',
            options={'ordering': ('-created_at',), 'permissions': [('retry_httprequestlog', 'Can send logged requests again')], 'verbose_name': 'HTTP request log', 'verbose_name_plural': 'HTTP request logs'},
        ),
        migrations.AlterField(
            model_name='httprequestlog',
            name='request_body_omission',
            field=models.CharField(blank=True, choices=[('disabled', 'Body storage disabled'), ('too_large', 'Body above the size limit'), ('binary', 'Body is not text'), ('streamed', 'Body was streamed'), ('unprepared', 'The request was never prepared')], max_length=16, verbose_name='request body omitted because'),
        ),
        migrations.AlterField(
            model_name='httprequestlog',
            name='response_body_omission',
            field=models.CharField(blank=True, choices=[('disabled', 'Body storage disabled'), ('too_large', 'Body above the size limit'), ('binary', 'Body is not text'), ('streamed', 'Body was streamed'), ('unprepared', 'The request was never prepared')], max_length=16, verbose_name='response body omitted because'),
        ),
        migrations.AddIndex(
            model_name='httprequestlog',
            index=models.Index(fields=['created_at'], name='outbound_ht_created_2cfd24_idx'),
        ),
    ]
