# Generated by Django 6.1 on 2026-08-25 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='message id')),
                ('from_email', models.CharField(max_length=254, verbose_name='from')),
                ('to', models.JSONField(default=list, verbose_name='to')),
                ('cc', models.JSONField(blank=True, default=list, verbose_name='cc')),
                ('bcc', models.JSONField(blank=True, default=list, verbose_name='bcc')),
                ('reply_to', models.JSONField(blank=True, default=list, verbose_name='reply to')),
                ('subject', models.CharField(blank=True, max_length=998, verbose_name='subject')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('html_body', models.TextField(blank=True, verbose_name='HTML body')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='headers')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='attachments')),
                ('raw_message', models.BinaryField(blank=True, null=True, verbose_name='raw MIME message')),
                ('body_omission', models.CharField(blank=True, choices=[('disabled', 'Body storage disabled'), ('too_large', 'Message above the size limit')], max_length=16, verbose_name='body omitted because')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='context')),
            ],
            options={
                'verbose_name': 'email log',
                'verbose_name_plural': 'email logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='outbound_ma_status_6cabf3_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailSendAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('trigger', models.CharField(choices=[('send', 'Initial send'), ('admin', 'Retry from the admin'), ('command', 'Retry from a management command'), ('code', 'Retry from code')], max_length=16, verbose_name='trigger')),
                ('succeeded', models.BooleanField(verbose_name='succeeded')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='outbound_mail.emaillog', verbose_name='email log')),
            ],
            options={
                'verbose_name': 'send attempt',
                'verbose_name_plural': 'send attempts',
                'ordering': ('-started_at',),
            },
        ),
    ]
