# Generated by Django 6.1 on 2026-08-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ('-created_at',), 'permissions': [('retry_emaillog', 'Can send logged messages again')], 'verbose_name': 'email log', 'verbose_name_plural': 'email logs'},
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['created_at'], name='outbound_ma_created_8677fa_idx'),
        ),
    ]
